const express = require('express');
const crypto = require('crypto');
const { Pool } = require('pg');
const path = require('path');

const app = express();
app.use(express.json({limit:'2mb'}));
app.use(express.urlencoded({extended:true}));

const DATABASE_URL = process.env.DATABASE_URL;
if (!DATABASE_URL) console.warn('DATABASE_URL belum diatur.');
let pool = new Pool({connectionString:DATABASE_URL, ssl:DATABASE_URL ? {rejectUnauthorized:false} : false, max:5});
const BOOTSTRAP_DATABASE_URL = DATABASE_URL;
let activeDatabaseUrl = DATABASE_URL;
const DB_CONFIG_SECRET = process.env.DB_CONFIG_SECRET || process.env.SESSION_SECRET || 'change-this-secret';

const DEFAULT_SETTINGS={
  jenis:[{id:1,nama:'Mobile Legend',prefix:'ML-'},{id:2,nama:'Clash of Clans',prefix:'COC-'},{id:3,nama:'Free Fire',prefix:'FF-'},{id:4,nama:'Honor of Kings',prefix:'HOK-'},{id:5,nama:'Lainnya',prefix:'ACC-'}],
  tempat:[{id:1,nama:'Itemku',potongan:10},{id:2,nama:'Tokoku',potongan:0},{id:3,nama:'G2G',potongan:0},{id:4,nama:'Facebook',potongan:0},{id:5,nama:'Lainnya',potongan:0}],
  metode_beli:[{id:1,nama:'Seabank'},{id:2,nama:'Dana'},{id:3,nama:'Transfer'},{id:4,nama:'Saldo'},{id:5,nama:'Lainnya'}],
  metode_bayar:[{id:1,nama:'Saldo Itemku',garansi:30},{id:2,nama:'Dana',garansi:0},{id:3,nama:'Transfer',garansi:0},{id:4,nama:'Seabank',garansi:0},{id:5,nama:'Lainnya',garansi:0}]
};

let initPromise;
let bootstrapPromise;
function encryptDbUrl(url){const iv=crypto.randomBytes(12);const key=crypto.createHash('sha256').update(DB_CONFIG_SECRET).digest();const c=crypto.createCipheriv('aes-256-gcm',key,iv);const enc=Buffer.concat([c.update(url,'utf8'),c.final()]);return [iv.toString('base64url'),c.getAuthTag().toString('base64url'),enc.toString('base64url')].join('.');}
function decryptDbUrl(blob){const [ivB,tagB,dataB]=String(blob||'').split('.');if(!ivB||!tagB||!dataB)throw new Error('Konfigurasi database rusak');const key=crypto.createHash('sha256').update(DB_CONFIG_SECRET).digest();const d=crypto.createDecipheriv('aes-256-gcm',key,iv);d.setAuthTag(Buffer.from(tagB,'base64url'));return Buffer.concat([d.update(Buffer.from(dataB,'base64url')),d.final()]).toString('utf8');}
async function bootstrap(){
  if(bootstrapPromise) return bootstrapPromise;
  bootstrapPromise=(async()=>{
    if(!BOOTSTRAP_DATABASE_URL) throw new Error('DATABASE_URL belum diatur di Vercel.');
    await pool.query(`CREATE TABLE IF NOT EXISTS app_db_config(id INTEGER PRIMARY KEY CHECK(id=1), encrypted_url TEXT NOT NULL, updated_at TIMESTAMPTZ DEFAULT NOW());`);
    const r=await pool.query('SELECT encrypted_url FROM app_db_config WHERE id=1');
    if(r.rowCount){
      try{const configured=decryptDbUrl(r.rows[0].encrypted_url); if(configured && configured!==activeDatabaseUrl){const np=new Pool({connectionString:configured,ssl:{rejectUnauthorized:false},max:5});await np.query('SELECT 1');const old=pool;pool=np;activeDatabaseUrl=configured;await old.end().catch(()=>{});}}catch(e){console.warn('Konfigurasi DB tersimpan tidak dapat dipakai, memakai DATABASE_URL:',e.message);}
    }
  })();
  return bootstrapPromise;
}
async function ensureSchema(){
    await pool.query(`CREATE TABLE IF NOT EXISTS users(id SERIAL PRIMARY KEY, username TEXT UNIQUE NOT NULL, password TEXT NOT NULL);`);
    await pool.query(`CREATE TABLE IF NOT EXISTS settings(id SERIAL PRIMARY KEY, type TEXT NOT NULL, nama TEXT NOT NULL, prefix TEXT, potongan NUMERIC DEFAULT 0, garansi INTEGER DEFAULT 0, UNIQUE(type,nama));`);
    await pool.query(`CREATE TABLE IF NOT EXISTS sales(id SERIAL PRIMARY KEY, kode TEXT, tanggal_beli TEXT, jenis TEXT, harga_beli BIGINT DEFAULT 0, info TEXT, kode_cadangan JSONB DEFAULT '[]'::jsonb, metode_beli TEXT, tempat TEXT, tanggal_jual TEXT, tanggal_konfirmasi TEXT, metode_bayar TEXT, garansi INTEGER DEFAULT 0, pembeli TEXT, pesanan TEXT, harga_jual BIGINT DEFAULT 0, potongan BIGINT DEFAULT 0, diterima BIGINT DEFAULT 0, keuntungan BIGINT DEFAULT 0, hackback BOOLEAN DEFAULT FALSE, tanggal_hackback TEXT, created_at TIMESTAMPTZ DEFAULT NOW());`);
    await pool.query(`ALTER TABLE sales ADD COLUMN IF NOT EXISTS bukti_status TEXT DEFAULT 'belum';`);
    await pool.query(`UPDATE sales SET bukti_status='belum' WHERE bukti_status IS NULL OR bukti_status='' OR bukti_status NOT IN ('belum','screenshot','upload');`);
    await pool.query(`CREATE TABLE IF NOT EXISTS expenses(id SERIAL PRIMARY KEY, tanggal TEXT NOT NULL, jenis TEXT NOT NULL, keterangan TEXT DEFAULT '', jumlah BIGINT NOT NULL, created_at TIMESTAMPTZ DEFAULT NOW());`);
    const u=await pool.query('SELECT id FROM users WHERE username=$1',['admin']);
    if(!u.rowCount) await pool.query('INSERT INTO users(username,password) VALUES($1,$2)',['admin','admin123']);
    const c=await pool.query('SELECT COUNT(*)::int n FROM settings');
    if(c.rows[0].n===0){ for(const [type,items] of Object.entries(DEFAULT_SETTINGS)) for(const x of items) await pool.query('INSERT INTO settings(type,nama,prefix,potongan,garansi) VALUES($1,$2,$3,$4,$5)',[type,x.nama,x.prefix||null,x.potongan||0,x.garansi||0]); }
}
async function init(){
  if(initPromise) return initPromise;
  initPromise=(async()=>{await bootstrap(); await ensureSchema();})();
  return initPromise;
}

function parseCookies(req){const out={};String(req.headers.cookie||'').split(';').forEach(p=>{const i=p.indexOf('=');if(i>0)out[p.slice(0,i).trim()]=decodeURIComponent(p.slice(i+1));});return out;}
function sign(value){return crypto.createHmac('sha256',process.env.SESSION_SECRET||'change-this-secret').update(value).digest('base64url');}
function setSession(res,user){const payload=Buffer.from(JSON.stringify({id:user.id,username:user.username,exp:Date.now()+1000*60*60*24*7})).toString('base64url');const token=payload+'.'+sign(payload);res.setHeader('Set-Cookie',`session=${token}; Path=/; HttpOnly; SameSite=Lax; Secure`);}
function getSession(req){try{const t=parseCookies(req).session||'';const [p,s]=t.split('.');if(!p||!s||s!==sign(p))return null;const x=JSON.parse(Buffer.from(p,'base64url').toString());if(x.exp<Date.now())return null;return x;}catch{return null;}}
function auth(req,res,next){const u=getSession(req);if(!u)return res.status(401).json({error:'Belum login'});req.user=u;next();}
function rupiahNumber(v){const s=String(v??'').replace(/[^0-9]/g,'');return s?Number(s):0;}
function cleanCodes(v){let a=Array.isArray(v)?v:(v?[v]:[]);a=a.map(x=>String(x||'').replace(/\s+/g,'')).filter(Boolean);if(a.length>10)throw new Error('Maksimal 10 kode cadangan');for(const c of a)if(!/^\d{8}$/.test(c))throw new Error('Setiap kode cadangan harus tepat 8 digit angka');return a;}
async function settingsObj(){const r=await pool.query('SELECT * FROM settings ORDER BY id');const o={jenis:[],tempat:[],metode_beli:[],metode_bayar:[]};for(const x of r.rows){if(!o[x.type])o[x.type]=[];o[x.type].push({id:x.id,nama:x.nama,prefix:x.prefix,potongan:Number(x.potongan)||0,garansi:Number(x.garansi)||0});}return o;}

app.post('/api/login',async(req,res)=>{try{await init();const r=await pool.query('SELECT id,username,password FROM users WHERE username=$1 AND password=$2',[String(req.body.username||''),String(req.body.password||'')]);if(!r.rowCount)return res.status(401).json({error:'Username atau password salah'});setSession(res,r.rows[0]);res.json({ok:true,username:r.rows[0].username});}catch(e){res.status(500).json({error:e.message});}});
app.post('/api/logout',(req,res)=>{res.setHeader('Set-Cookie','session=; Path=/; Max-Age=0; HttpOnly; SameSite=Lax; Secure');res.json({ok:true});});
app.get('/api/me',(req,res)=>{const u=getSession(req);res.json({loggedIn:!!u,user:u||null});});
app.get('/api/db/status',auth,async(req,res)=>{try{await init();const r=await pool.query('SELECT current_database() AS database, version() AS version');res.json({ok:true,connected:true,database:r.rows[0].database,server:r.rows[0].version.split(' on ')[0],activeIsBootstrap:activeDatabaseUrl===BOOTSTRAP_DATABASE_URL});}catch(e){res.status(500).json({connected:false,error:e.message});}});
app.post('/api/db/test',auth,async(req,res)=>{let p;try{const url=String(req.body.database_url||'').trim();if(!url)return res.status(400).json({error:'DATABASE_URL wajib diisi'});p=new Pool({connectionString:url,ssl:{rejectUnauthorized:false},max:1,connectionTimeoutMillis:8000});const r=await p.query('SELECT current_database() AS database, NOW() AS now');res.json({ok:true,database:r.rows[0].database,now:r.rows[0].now});}catch(e){res.status(400).json({ok:false,error:e.message});}finally{if(p)await p.end().catch(()=>{});}});
app.post('/api/db/save',auth,async(req,res)=>{let np;try{const url=String(req.body.database_url||'').trim();if(!url)return res.status(400).json({error:'DATABASE_URL wajib diisi'});np=new Pool({connectionString:url,ssl:{rejectUnauthorized:false},max:5,connectionTimeoutMillis:8000});await np.query('SELECT 1');const b=new Pool({connectionString:BOOTSTRAP_DATABASE_URL,ssl:{rejectUnauthorized:false},max:1});await b.query(`CREATE TABLE IF NOT EXISTS app_db_config(id INTEGER PRIMARY KEY CHECK(id=1), encrypted_url TEXT NOT NULL, updated_at TIMESTAMPTZ DEFAULT NOW());`);await b.query('INSERT INTO app_db_config(id,encrypted_url,updated_at) VALUES(1,$1,NOW()) ON CONFLICT(id) DO UPDATE SET encrypted_url=EXCLUDED.encrypted_url,updated_at=NOW()',[encryptDbUrl(url)]);await b.end();const old=pool;pool=np;activeDatabaseUrl=url;initPromise=null;await ensureSchema();res.json({ok:true,message:'Database berhasil disimpan dan diaktifkan. DATABASE_URL bootstrap tetap diperlukan di Vercel agar konfigurasi ini dipulihkan setelah redeploy.'});}catch(e){if(np)await np.end().catch(()=>{});res.status(400).json({ok:false,error:e.message});}});
app.post('/api/db/use-bootstrap',auth,async(req,res)=>{try{if(!BOOTSTRAP_DATABASE_URL)return res.status(400).json({error:'DATABASE_URL bootstrap tidak tersedia'});const np=new Pool({connectionString:BOOTSTRAP_DATABASE_URL,ssl:{rejectUnauthorized:false},max:5});await np.query('SELECT 1');const old=pool;pool=np;activeDatabaseUrl=BOOTSTRAP_DATABASE_URL;initPromise=null;await ensureSchema();await old.end().catch(()=>{});res.json({ok:true,message:'Kembali ke DATABASE_URL bootstrap.'});}catch(e){res.status(500).json({error:e.message});}});

app.get('/api/settings',auth,async(req,res)=>{try{await init();res.json(await settingsObj());}catch(e){res.status(500).json({error:e.message});}});
app.post('/api/settings/:type',auth,async(req,res)=>{try{await init();const type=String(req.params.type),allowed=['jenis','tempat','metode_beli','metode_bayar'];if(!allowed.includes(type))return res.status(400).json({error:'Jenis pengaturan tidak valid'});const nama=String(req.body.nama||'').trim();if(!nama)return res.status(400).json({error:'Nama wajib diisi'});let prefix=null,pot=0,gar=0;if(type==='jenis'){prefix=String(req.body.prefix||'ACC-').trim().toUpperCase();if(!/^[A-Z0-9_-]+-$/.test(prefix))return res.status(400).json({error:'Prefix harus diakhiri tanda -'});}if(type==='tempat')pot=Math.max(0,Math.min(100,Number(req.body.potongan)||0));if(type==='metode_bayar')gar=Math.max(0,Number(req.body.garansi)||0);const r=await pool.query('INSERT INTO settings(type,nama,prefix,potongan,garansi) VALUES($1,$2,$3,$4,$5) RETURNING *',[type,nama,prefix,pot,gar]);res.json(r.rows[0]);}catch(e){res.status(400).json({error:e.code==='23505'?'Nama sudah ada':e.message});}});
app.put('/api/settings/:type/:id',auth,async(req,res)=>{try{await init();const type=String(req.params.type),id=Number(req.params.id),nama=String(req.body.nama||'').trim();if(!nama)return res.status(400).json({error:'Nama wajib diisi'});let prefix=null,pot=0,gar=0;if(type==='jenis'){prefix=String(req.body.prefix||'ACC-').trim().toUpperCase();if(!/^[A-Z0-9_-]+-$/.test(prefix))return res.status(400).json({error:'Prefix harus diakhiri tanda -'});}if(type==='tempat')pot=Math.max(0,Math.min(100,Number(req.body.potongan)||0));if(type==='metode_bayar')gar=Math.max(0,Number(req.body.garansi)||0);const r=await pool.query('UPDATE settings SET nama=$1,prefix=$2,potongan=$3,garansi=$4 WHERE id=$5 AND type=$6 RETURNING *',[nama,prefix,pot,gar,id,type]);if(!r.rowCount)return res.status(404).json({error:'Data pengaturan tidak ditemukan'});res.json(r.rows[0]);}catch(e){res.status(400).json({error:e.code==='23505'?'Nama sudah ada':e.message});}});
app.delete('/api/settings/:type/:id',auth,async(req,res)=>{try{await init();await pool.query('DELETE FROM settings WHERE id=$1 AND type=$2',[Number(req.params.id),String(req.params.type)]);res.json({ok:true});}catch(e){res.status(500).json({error:e.message});}});

app.get('/api/expenses',auth,async(req,res)=>{try{await init();const from=String(req.query.from||''),to=String(req.query.to||''),q=String(req.query.q||'').toLowerCase();const r=await pool.query('SELECT * FROM expenses ORDER BY id DESC');res.json(r.rows.filter(x=>(!from||x.tanggal>=from)&&(!to||x.tanggal<=to)&&(!q||[x.jenis,x.keterangan].join(' ').toLowerCase().includes(q))).map(x=>({...x,id:Number(x.id),jumlah:Number(x.jumlah)})));}catch(e){res.status(500).json({error:e.message});}});
app.post('/api/expenses',auth,async(req,res)=>{try{await init();const jenis=String(req.body.jenis||'').trim(),keterangan=String(req.body.keterangan||'').trim(),tanggal=String(req.body.tanggal||''),jumlah=rupiahNumber(req.body.jumlah);if(!jenis||!tanggal||jumlah<=0)return res.status(400).json({error:'Tanggal, jenis biaya, dan jumlah wajib diisi'});const r=await pool.query('INSERT INTO expenses(tanggal,jenis,keterangan,jumlah) VALUES($1,$2,$3,$4) RETURNING *',[tanggal,jenis,keterangan,jumlah]);res.json({id:Number(r.rows[0].id)});}catch(e){res.status(500).json({error:e.message});}});
app.put('/api/expenses/:id',auth,async(req,res)=>{try{await init();const jenis=String(req.body.jenis||'').trim(),keterangan=String(req.body.keterangan||'').trim(),tanggal=String(req.body.tanggal||''),jumlah=rupiahNumber(req.body.jumlah);if(!jenis||!tanggal||jumlah<=0)return res.status(400).json({error:'Tanggal, jenis biaya, dan jumlah wajib diisi'});const r=await pool.query('UPDATE expenses SET tanggal=$1,jenis=$2,keterangan=$3,jumlah=$4 WHERE id=$5 RETURNING id',[tanggal,jenis,keterangan,jumlah,Number(req.params.id)]);if(!r.rowCount)return res.status(404).json({error:'Biaya tidak ditemukan'});res.json({ok:true});}catch(e){res.status(500).json({error:e.message});}});
app.delete('/api/expenses/:id',auth,async(req,res)=>{try{await init();await pool.query('DELETE FROM expenses WHERE id=$1',[Number(req.params.id)]);res.json({ok:true});}catch(e){res.status(500).json({error:e.message});}});

function mapSale(x){const bukti=['belum','screenshot','upload'].includes(String(x.bukti_status||''))?String(x.bukti_status):'belum';return {...x,id:Number(x.id),harga_beli:Number(x.harga_beli)||0,harga_jual:Number(x.harga_jual)||0,potongan:Number(x.potongan)||0,diterima:Number(x.diterima)||0,keuntungan:Number(x.keuntungan)||0,garansi:Number(x.garansi)||0,bukti_status:bukti,kode_cadangan:Array.isArray(x.kode_cadangan)?x.kode_cadangan:[]};}
app.get('/api/sales',auth,async(req,res)=>{try{await init();const r=await pool.query('SELECT * FROM sales ORDER BY id DESC');const q=String(req.query.q||'').toLowerCase(),status=String(req.query.status||''),jenis=String(req.query.jenis||''),bukti=String(req.query.bukti||''),from=String(req.query.from||''),to=String(req.query.to||'');const rows=r.rows.map(mapSale).filter(x=>{const hay=[x.kode,x.jenis,x.info,...x.kode_cadangan,x.pembeli,x.pesanan,x.tempat].join(' ').toLowerCase();const st=x.hackback?'HB':(x.tanggal_jual?'Sold':'Available');const d=x.hackback?(x.tanggal_hackback||x.tanggal_jual||''):(x.tanggal_jual||'');return(!q||hay.includes(q))&&(!status||status===st)&&(!jenis||jenis===x.jenis)&&(!bukti||bukti===x.bukti_status)&&(!from||d>=from)&&(!to||d<=to);});res.json(rows);}catch(e){res.status(500).json({error:e.message});}});

app.post('/api/sales',auth,async(req,res)=>{try{await init();const codes=cleanCodes(req.body.kode_cadangan),r=await pool.query(`INSERT INTO sales(kode,tanggal_beli,jenis,harga_beli,info,kode_cadangan,metode_beli) VALUES($1,$2,$3,$4,$5,$6,$7) RETURNING id`,[String(req.body.kode||''),String(req.body.tanggal_beli||''),String(req.body.jenis||''),rupiahNumber(req.body.harga_beli),String(req.body.info||''),JSON.stringify(codes),String(req.body.metode_beli||'')]);res.json({id:Number(r.rows[0].id)});}catch(e){res.status(400).json({error:e.message});}});
app.put('/api/sales/:id/account',auth,async(req,res)=>{try{await init();const codes=cleanCodes(req.body.kode_cadangan);const id=Number(req.params.id),r=await pool.query(`UPDATE sales SET kode=$1,tanggal_beli=$2,jenis=$3,harga_beli=$4,info=$5,kode_cadangan=$6,metode_beli=$7,keuntungan=GREATEST(0,diterima-$4) WHERE id=$8 RETURNING id`,[String(req.body.kode||''),String(req.body.tanggal_beli||''),String(req.body.jenis||''),rupiahNumber(req.body.harga_beli),String(req.body.info||''),JSON.stringify(codes),String(req.body.metode_beli||''),id]);if(!r.rowCount)return res.status(404).json({error:'Data tidak ditemukan'});res.json({ok:true});}catch(e){res.status(400).json({error:e.message});}});
app.put('/api/sales/:id/penjualan',auth,async(req,res)=>{try{await init();const id=Number(req.params.id),s=(await pool.query('SELECT harga_beli FROM sales WHERE id=$1',[id])).rows[0];if(!s)return res.status(404).json({error:'Data tidak ditemukan'});const st=await settingsObj(),tempat=String(req.body.tempat||''),bayar=String(req.body.metode_bayar||''),tc=st.tempat.find(x=>x.nama===tempat),bc=st.metode_bayar.find(x=>x.nama===bayar),jual=rupiahNumber(req.body.harga_jual),pot=Math.round(jual*(Number(tc?.potongan)||0)/100),gar=Number(bc?.garansi)||0,dit=Math.max(0,jual-pot),unt=Math.max(0,dit-Number(s.harga_beli));await pool.query(`UPDATE sales SET tempat=$1,tanggal_jual=$2,tanggal_konfirmasi=$3,metode_bayar=$4,garansi=$5,pembeli=$6,pesanan=$7,harga_jual=$8,potongan=$9,diterima=$10,keuntungan=$11 WHERE id=$12`,[tempat,String(req.body.tanggal_jual||''),String(req.body.tanggal_konfirmasi||''),bayar,gar,String(req.body.pembeli||''),String(req.body.pesanan||''),jual,pot,dit,unt,id]);res.json({ok:true,potongan:pot,garansi:gar});}catch(e){res.status(400).json({error:e.message});}});
app.put('/api/sales/:id/bukti',auth,async(req,res)=>{try{await init();const id=Number(req.params.id),status=String(req.body.bukti_status||'').toLowerCase();if(!['belum','screenshot','upload'].includes(status))return res.status(400).json({error:'Status bukti tidak valid'});const r=await pool.query('UPDATE sales SET bukti_status=$1 WHERE id=$2 RETURNING id,bukti_status',[status,id]);if(!r.rowCount)return res.status(404).json({error:'Data tidak ditemukan'});res.json({ok:true,id:Number(r.rows[0].id),bukti_status:r.rows[0].bukti_status});}catch(e){res.status(500).json({error:e.message});}});

app.put('/api/sales/:id/hackback',auth,async(req,res)=>{try{await init();const id=Number(req.params.id),enabled=Boolean(req.body.enabled);const d=enabled?(String(req.body.tanggal_hackback||'')||new Date().toISOString().slice(0,10)):'';const r=await pool.query('UPDATE sales SET hackback=$1,tanggal_hackback=$2 WHERE id=$3 RETURNING id',[enabled,d,id]);if(!r.rowCount)return res.status(404).json({error:'Data tidak ditemukan'});res.json({ok:true,hackback:enabled});}catch(e){res.status(500).json({error:e.message});}});
app.delete('/api/sales/:id',auth,async(req,res)=>{try{await init();await pool.query('DELETE FROM sales WHERE id=$1',[Number(req.params.id)]);res.json({ok:true});}catch(e){res.status(500).json({error:e.message});}});

app.get('/api/stats',auth,async(req,res)=>{try{await init();const from=String(req.query.from||''),to=String(req.query.to||'');const all=(await pool.query('SELECT * FROM sales')).rows.map(mapSale),expenses=(await pool.query('SELECT * FROM expenses')).rows.map(x=>({...x,id:Number(x.id),jumlah:Number(x.jumlah)}));const sold=all.filter(x=>x.tanggal_jual&&!x.hackback&&(!from||x.tanggal_jual>=from)&&(!to||x.tanggal_jual<=to)),hb=all.filter(x=>x.hackback&&(!from||x.tanggal_hackback>=from)&&(!to||x.tanggal_hackback<=to)),ex=expenses.filter(x=>(!from||x.tanggal>=from)&&(!to||x.tanggal<=to));const omzet=sold.reduce((a,x)=>a+x.harga_jual,0),potongan=sold.reduce((a,x)=>a+x.potongan,0),diterima=sold.reduce((a,x)=>a+x.diterima,0),modal=sold.reduce((a,x)=>a+x.harga_beli,0),biayaLain=ex.reduce((a,x)=>a+x.jumlah,0),hackbackLoss=hb.reduce((a,x)=>a+x.harga_beli,0),untungKotor=omzet-potongan,untungBersihSold=diterima-modal,untungBersihAkhir=untungBersihSold-biayaLain-hackbackLoss;const monthlyMap={};sold.forEach(x=>{const b=x.tanggal_jual.slice(0,7);if(!monthlyMap[b])monthlyMap[b]={bulan:b,jumlah:0,modal:0,omzet:0,potongan:0,kotor:0,bersih:0,biaya:0};monthlyMap[b].jumlah++;monthlyMap[b].modal+=x.harga_beli;monthlyMap[b].omzet+=x.harga_jual;monthlyMap[b].potongan+=x.potongan;monthlyMap[b].kotor+=x.harga_jual-x.potongan;monthlyMap[b].bersih+=x.keuntungan;});ex.forEach(x=>{const b=x.tanggal.slice(0,7);if(!monthlyMap[b])monthlyMap[b]={bulan:b,jumlah:0,modal:0,omzet:0,potongan:0,kotor:0,bersih:0,biaya:0};monthlyMap[b].biaya+=x.jumlah;monthlyMap[b].bersih-=x.jumlah;});const monthly=Object.values(monthlyMap).sort((a,b)=>b.bulan.localeCompare(a.bulan)).slice(0,12);const detail=sold.map(x=>({...x,status:'Sold'}));res.json({total:all.filter(x=>(x.tanggal_jual||'')&&(!from||x.tanggal_jual>=from)&&(!to||x.tanggal_jual<=to)).length,sold:sold.length,hackback:hb.length,hackbackLoss,beli:modal,omzet,potongan,diterima,biayaLain,untungBersihSold,untungKotor,untungBersih:untungBersihAkhir,untungBersihAkhir,monthly,detail,expenses:ex});}catch(e){res.status(500).json({error:e.message});}});

app.get('/api/export',auth,async(req,res)=>{try{await init();const rows=(await pool.query('SELECT * FROM sales ORDER BY id')).rows.map(mapSale);const headers=['Kode Akun','Status','Bukti','Tanggal Beli','Jenis','Harga Beli','Informasi Akun','Kode Cadangan 8 Digit','Metode Pembelian','Tempat Penjualan','Tanggal Terjual','Tanggal Konfirmasi','Metode Pembayaran','Garansi','Nama Pembeli','Nomor Pesanan','Harga Terjual','Potongan','Diterima Bersih','Keuntungan'];const data=rows.map(x=>[x.kode,x.hackback?'HB':(x.tanggal_jual?'Sold':'Available'),x.bukti_status,x.tanggal_beli,x.jenis,x.harga_beli,x.info,x.kode_cadangan.join(' | '),x.metode_beli,x.tempat,x.tanggal_jual,x.tanggal_konfirmasi,x.metode_bayar,x.garansi,x.pembeli,x.pesanan,x.harga_jual,x.potongan,x.diterima,x.keuntungan]);const csv=[headers,...data].map(r=>r.map(v=>`"${String(v??'').replaceAll('"','""')}"`).join(',')).join('\n');res.setHeader('Content-Type','text/csv; charset=utf-8');res.setHeader('Content-Disposition','attachment; filename="laporan-penjualan.csv"');res.send('\ufeff'+csv);}catch(e){res.status(500).json({error:e.message});}});

app.get('*',(req,res)=>res.sendFile(path.join(process.cwd(),'public','index.html')));
module.exports=app;
